name: sos_mascotas
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  provider: ^6.1.5+1
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  http: ^1.5.0
  image_picker: ^1.2.0
  firebase_storage: ^13.0.1
  dotted_border: ^2.0.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.2
  video_trimmer: ^5.0.0
  video_player: ^2.9.0
  firebase_messaging: ^16.0.3
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^19.4.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  image: ^4.0.0
  firebase_app_check: ^0.4.1+1
  responsive_framework: ^1.2.0
  url_launcher: ^6.3.2
  lottie: ^3.1.0
  tflite_flutter: ^0.11.0
  google_sign_in: ^5.4.0
  share_plus: ^12.0.1
  pdf: ^3.11.3
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.1
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/keys/service_account.json
    - assets/model/animales.tflite
    - assets/model/extractor_animales.tflite
    - assets/avatars/
    - assets/Video/video.mp4
    - assets/imagen/HOSPITAL.jpeg
    - assets/imagen/ANIMALCARE.jpeg
    - assets/imagen/imagen1.png
    - assets/imagen/imagen2.jpeg
    - assets/imagen/imagen3.webp
    - assets/imagen/imagen4.jpeg
    - assets/imagen/imagen5.avif
    - assets/imagen/imagen6.avif
    - assets/imagen/imagen7.png
    - assets/imagen/imagen8.webp
    - assets/imagen/imagen9.jpg
    - assets/imagen/imagen10.jpg
    - assets/imagen/imagen11.jpg
    - assets/imagen/imagen12.avif
    